driver:
  name: vagrant
  synced_folders:
      - ["../", "/cookbooks"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: haproxy
    run_list:
      - recipe[haproxy::default]
